vim.cmd('source ~/.config/nvim/config.vim')
require('plugins/lsp')
 --require('coc')
require('completions')
require('jsx_pretty')
require('telescope_map')
require('indenting')
-- require('tree-sit')
require('lualine').setup()
require('trouble_diag')
require('treenerdy')
require('neogem')
require('lualoine')
require('nullls')
